import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "./components/Header";
import Nav from "./components/Nav";

import { Suspense } from "react";
import Providers from "../providers";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <main className="min-h-full flex flex-col">
      <Suspense fallback={null}>
        <Providers>
          <Header />
          <main className="flex-1 w-full max-w-[1400px] mx-auto pt-[60px] md:pt-[70px] pb-[70px] md:pb-0">
            {children}
          </main>
        </Providers>
        <Footer />
      </Suspense>
    </main>
  );
}
