import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "./components/Header";
import Nav from "./components/Nav";
import CartProvider from "../../contexts/CartContext";
import { UserProvider } from "../../contexts/UserContext";
import ProductProvider from "@/src/contexts/ProductContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="min-h-full flex flex-col">
      <ProductProvider>
        <UserProvider>
          <CartProvider>
            <Header />
            <div className="flex-1 overflow-y-auto pb-16">{children}</div>
            <Nav />
          </CartProvider>
        </UserProvider>
      </ProductProvider>
    </main>
  );
}
